# Generated by Django 3.2.18 on 2023-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutbuttonpluginmodel',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
