# Generated by Django 3.2.18 on 2023-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_checkoutbuttonpluginmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutbuttonpluginmodel',
            name='outlined',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
