# Generated by Django 3.1.14 on 2022-01-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemForRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Prix')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('itemforrent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.itemforrent')),
                ('visible', models.BooleanField(default=True)),
                ('reservable', models.BooleanField(default=True)),
                ('support', models.URLField()),
                ('spec', models.TextField()),
                ('subscriber_price', models.FloatField()),
                ('photo', models.ImageField(upload_to='machines')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory')),
            ],
            bases=('machines.itemforrent',),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.itemforrent')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('itemforrent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.itemforrent')),
                ('level', models.CharField(choices=[('BEG', 'Débutant'), ('INT', 'Intermédiaire'), ('ADV', 'Avancé')], max_length=3, verbose_name='Niveau')),
                ('duration', models.DurationField(verbose_name='Durée')),
                ('photo', models.ImageField(upload_to='trainings', verbose_name='Photo')),
                ('machine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory', verbose_name='Catégorie de machine')),
            ],
            bases=('machines.itemforrent',),
        ),
        migrations.CreateModel(
            name='OutcomeListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTodoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seen_in_training', models.BooleanField(default=False)),
                ('sort', models.PositiveSmallIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='DIYListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('url', models.URLField(blank=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
            ],
        ),
    ]
