# Generated by Django 3.2.16 on 2022-11-16 20:33

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemForRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tarifs')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Spécification')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('itemforrent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.itemforrent')),
                ('visible', models.BooleanField(default=True)),
                ('reservable', models.BooleanField(default=True)),
                ('support', models.URLField()),
                ('spec', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Spécification')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('subscriber_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Tarifs d'inscription")),
                ('photo', models.ImageField(upload_to='machines')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinegroup')),
            ],
            bases=('machines.itemforrent',),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('itemforrent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.itemforrent')),
                ('level', models.CharField(choices=[('BEG', 'Débutant'), ('INT', 'Intermédiaire'), ('ADV', 'Avancé')], max_length=3, verbose_name='Niveau')),
                ('duration', models.DurationField(help_text='Utiliser le format HH:MM:SS', verbose_name='Durée')),
                ('header', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Chapeau')),
                ('support', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Matériel de cours')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('photo', models.ImageField(upload_to='trainings', verbose_name='Photo')),
                ('machine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory', verbose_name='Catégorie de machine')),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('machines.itemforrent',),
        ),
        migrations.CreateModel(
            name='MachineTodoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seen_in_training', models.BooleanField(default=False)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='machines_trainingslistpluginmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Réponse')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.itemforrent')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons', verbose_name='Icon')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('href', models.URLField(verbose_name='Lien')),
                ('about', models.ManyToManyField(to='machines.ItemForRent')),
            ],
        ),
        migrations.CreateModel(
            name='ToolsMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.tools')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolsTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.tools')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
