# Generated by Django 3.1.14 on 2022-04-08 12:58

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemForRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Specifications')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('itemforrent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.itemforrent')),
                ('visible', models.BooleanField(default=True)),
                ('reservable', models.BooleanField(default=True)),
                ('support', models.URLField()),
                ('spec', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Specifications')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('subscriber_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Subscriber price')),
                ('photo', models.ImageField(upload_to='machines')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinegroup')),
            ],
            bases=('machines.itemforrent',),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Answer')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.itemforrent')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('itemforrent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.itemforrent')),
                ('level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Avancé')], max_length=3, verbose_name='Niveau')),
                ('duration', models.DurationField(help_text='Use the format HH:MM:SS', verbose_name='Durée')),
                ('header', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Header')),
                ('support', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Assistance')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('photo', models.ImageField(upload_to='trainings', verbose_name='Photo')),
                ('machine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory', verbose_name='Machine category')),
            ],
            bases=('machines.itemforrent',),
        ),
        migrations.CreateModel(
            name='OutcomeListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTodoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seen_in_training', models.BooleanField(default=False)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='DIYListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('url', models.URLField(blank=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
            ],
        ),
    ]
