# Generated by Django 3.2.15 on 2022-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforrent',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tarifs'),
        ),
    ]
