# Generated by Django 3.2.16 on 2022-11-20 16:19

from django.db import migrations
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_PR130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, verbose_name='Lien'),
        ),
    ]
