# Generated by Django 3.2.15 on 2022-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_itemforrent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
