# Generated by Django 3.2.16 on 2022-12-15 19:08

from django.db import migrations, models
import django.db.models.deletion
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    replaces = [('machines', '0003_alter_card_link'), ('machines', '0004_auto_20221120_1645'), ('machines', '0005_auto_20221123_0802')]

    dependencies = [
        ('machines', '0002_PR130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarifs'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif membre'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinecategory'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinegroup'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, to='machines.Material'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workshop',
            field=models.ManyToManyField(blank=True, null=True, to='machines.Workshop'),
        ),
    ]
