# Generated by Django 3.2.16 on 2022-11-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_card_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarifs'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif membre'),
        ),
    ]
