# Generated by Django 3.2.15 on 2022-10-13 07:12

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='machines_trainingslistpluginmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='spec',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Spécification'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='subscriber_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Tarifs d'inscription"),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Spécification'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(help_text='Utiliser le format HH:MM:SS', verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='training',
            name='header',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Chapeau'),
        ),
        migrations.AlterField(
            model_name='training',
            name='level',
            field=models.CharField(choices=[('BEG', 'Débutant'), ('INT', 'Intermédiaire'), ('ADV', 'Avancé')], max_length=3, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='training',
            name='machine_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory', verbose_name='Catégorie de machine'),
        ),
        migrations.AlterField(
            model_name='training',
            name='support',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Matériel de cours'),
        ),
    ]
