# Generated by Django 3.2.17 on 2023-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('machines', '0004_auto_20221222_0802'), ('machines', '0005_auto_20230125_1130'), ('machines', '0005_alter_itemforrent_full_price'), ('machines', '0006_merge_20230209_2150'), ('machines', '0007_alter_training_includ_free_machine_voucher')]

    dependencies = [
        ('machines', '0003_PR137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='highlightmachine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='toolmachine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tooltraining',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingvalidation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Tarifs'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Tarifs'),
        ),
        migrations.AddField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Inclus bon machine'),
        ),
    ]
