# Generated by Django 3.2.17 on 2023-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20221222_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Inclus bon machine'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Tarifs'),
        ),
    ]
