# Generated by Django 3.2.16 on 2023-01-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20221222_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Tarifs'),
        ),
    ]
