# Generated by Django 3.2.17 on 2023-02-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_itemforrent_full_price'),
        ('machines', '0005_auto_20230125_1130'),
    ]

    operations = [
    ]
