# Generated by Django 3.2.18 on 2023-02-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('machines', '0006_merge_20230209_2150'), ('machines', '0007_alter_training_includ_free_machine_voucher'), ('machines', '0008_auto_20230212_2030'), ('machines', '0009_auto_20230215_2239')]

    dependencies = [
        ('machines', '0005_auto_20230125_1130'),
        ('machines', '0005_alter_itemforrent_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Inclus bon machine'),
        ),
        migrations.AddField(
            model_name='faq',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Include free machine voucher'),
        ),
    ]
