# Generated by Django 3.2.17 on 2023-02-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20230125_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Inclus bon machine'),
        ),
    ]
