# Generated by Django 3.2.15 on 2022-10-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
        migrations.RenameModel(
            old_name='ToolsMachine',
            new_name='ToolMachine',
        ),
        migrations.RenameModel(
            old_name='ToolsTraining',
            new_name='ToolTraining',
        ),
    ]
