# Generated by Django 3.2.18 on 2023-02-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_merge_20230209_2150_squashed_0009_auto_20230215_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Inclus bon machine'),
        ),
    ]
