# Generated by Django 3.2.17 on 2023-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_alter_training_includ_free_machine_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icon'),
        ),
    ]
