# Generated by Django 3.2.15 on 2022-10-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_remove_tool_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='href',
            new_name='link',
        ),
        migrations.AddField(
            model_name='tool',
            name='link_text',
            field=models.CharField(default='Télécharger', max_length=255, verbose_name='Link text'),
            preserve_default=False,
        ),
    ]
