# Generated by Django 3.2.20 on 2023-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_auto_20230218_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('machines', models.ManyToManyField(blank=True, null=True, to='machines.Machine')),
            ],
        ),
    ]
