# Generated by Django 3.2.18 on 2023-02-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20230212_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Include free machine voucher'),
        ),
    ]
