# Generated by Django 3.2.24 on 2024-03-03 10:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20230803_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='highlightmachine',
            options={'verbose_name': 'Machine highlight', 'verbose_name_plural': 'Machine highlights'},
        ),
        migrations.AlterModelOptions(
            name='machinecategory',
            options={'verbose_name': 'Machine category', 'verbose_name_plural': 'Machine categories'},
        ),
        migrations.AlterModelOptions(
            name='machinegroup',
            options={'verbose_name': 'Machine group', 'verbose_name_plural': 'Machine groups'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Specification', 'verbose_name_plural': 'Specifications'},
        ),
        migrations.AlterModelOptions(
            name='toolmachine',
            options={'verbose_name': 'Machine tool', 'verbose_name_plural': 'Machine tools'},
        ),
        migrations.AlterModelOptions(
            name='tooltraining',
            options={'verbose_name': 'Training tool', 'verbose_name_plural': 'Training tools'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshops'},
        ),
        migrations.AlterField(
            model_name='card',
            name='link_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link text'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=25, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='header',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Premium Price'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(help_text='Use the format HH:MM:SS', verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='training',
            name='includ_free_machine_voucher',
            field=models.BooleanField(default=True, verbose_name='Include free machine voucher'),
        ),
        migrations.AlterField(
            model_name='training',
            name='level',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Avancé')], max_length=3, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='training',
            name='machine_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinecategory', verbose_name='Machine category'),
        ),
    ]
