# Generated by Django 3.2.15 on 2022-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220312_1941'),
        ('machines', '0008_auto_20221015_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='notification',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
