# Generated by Django 3.2.25 on 2024-03-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('machines', '0009_auto_20240303_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_machines.pricemodel_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='machine',
            name='premium_price',
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(db_column='full_price', decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='material',
            field=models.ManyToManyField(blank=True, to='machines.Material'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workshop',
            field=models.ManyToManyField(blank=True, to='machines.Workshop'),
        ),
        migrations.AlterField(
            model_name='software',
            name='machines',
            field=models.ManyToManyField(blank=True, to='machines.Machine'),
        ),
        migrations.CreateModel(
            name='DegressiveFdmPriceModel',
            fields=[
                ('pricemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.pricemodel')),
                ('hourFactor', models.FloatField(default=0.7)),
                ('maxDivider', models.SmallIntegerField(default=30)),
                ('matterFactor', models.FloatField(default=0.075)),
                ('supportMatterFactor', models.FloatField(default=0.2)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('machines.pricemodel',),
        ),
        migrations.CreateModel(
            name='LinearPriceModel',
            fields=[
                ('pricemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.pricemodel')),
                ('full_price', models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Price')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('machines.pricemodel',),
        ),
        migrations.AddField(
            model_name='machine',
            name='price',
            field=models.ForeignKey(db_column='price', null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.pricemodel'),
        ),
    ]
