# Generated by Django 3.2.15 on 2022-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220312_1941'),
        ('machines', '0009_training_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='graduate',
            field=models.ManyToManyField(related_name='training_graduate', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='training',
            name='notification',
            field=models.ManyToManyField(related_name='training_notification', to='accounts.Profile'),
        ),
    ]
