# Generated by Django 3.2.15 on 2022-10-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220312_1941'),
        ('machines', '0010_auto_20221015_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='graduate',
        ),
        migrations.AlterField(
            model_name='training',
            name='notification',
            field=models.ManyToManyField(blank=True, related_name='training_notification', to='accounts.Profile'),
        ),
        migrations.CreateModel(
            name='TrainingValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
