# Generated by Django 3.2.25 on 2024-03-31 14:05

from django.db import migrations, models

def forward_change(apps, schema_editor):
    Training = apps.get_model('machines', 'Training')
    for t in Training.objects.all():
        t.full_price_new = t.full_price
        t.save()

def backward_change(apps, schema_editor):
    Training = apps.get_model('machines', 'Training')
    for t in Training.objects.all():
        t.full_price = t.full_price_new
        t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_auto_20240310_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='full_price_new',
            field=models.DecimalField(db_column='full_price', decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Price'),
        ),
        migrations.RunPython(forward_change, backward_change),
        migrations.RemoveField(
            model_name='itemforrent',
            name='full_price',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='full_price_new',
            new_name='full_price',
        ),
    ]
