# Generated by Django 4.2.17 on 2025-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_alter_machine_material_alter_machine_workshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecategory',
            name='training_required',
            field=models.BooleanField(default=False, help_text='Does this machine category require training validation?'),
        ),
    ]
