# Generated by Django 3.2.15 on 2022-10-16 21:47

import colorfield.fields
from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_auto_20221016_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemforrent',
            old_name='price',
            new_name='full_price',
        ),
        migrations.RemoveField(
            model_name='itemforrent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemforrent',
            name='title',
        ),
        migrations.AddField(
            model_name='itemforrent',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Premium Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AddField(
            model_name='machine',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AddField(
            model_name='machine',
            name='desc',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='machine',
            name='title',
            field=models.CharField(default='My machine', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AddField(
            model_name='training',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AddField(
            model_name='training',
            name='desc',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(default='My training', max_length=255),
            preserve_default=False,
        ),
    ]
