# Generated by Django 3.2.15 on 2022-10-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_auto_20221016_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingvalidation',
            old_name='user',
            new_name='profile',
        ),
    ]
