# Generated by Django 4.2.30 on 2026-06-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('machines', '0012_machinecategory_training_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='machine',
            name='premium_price',
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='full_price',
            field=models.DecimalField(db_column='full_price_old', decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Tarifs'),
        ),
        migrations.CreateModel(
            name='DegressiveFdmPriceModel',
            fields=[
                ('pricemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.pricemodel')),
                ('first_hour_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='First hour price')),
                ('hour_factor', models.FloatField(default=0.7)),
                ('max_divider', models.SmallIntegerField(default=30)),
                ('matter_factor', models.FloatField(default=0.075)),
                ('support_matter_factor', models.FloatField(default=0.2)),
            ],
            options={
                'abstract': False,
            },
            bases=('machines.pricemodel',),
        ),
        migrations.CreateModel(
            name='LinearPriceModel',
            fields=[
                ('pricemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.pricemodel')),
                ('full_price', models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Tarifs')),
            ],
            options={
                'abstract': False,
            },
            bases=('machines.pricemodel',),
        ),
        migrations.AddField(
            model_name='machine',
            name='price',
            field=models.ForeignKey(db_column='price', null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.pricemodel'),
        ),
    ]
