# Generated by Django 3.2.15 on 2022-10-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220312_1941'),
        ('machines', '0013_rename_user_trainingvalidation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='notification',
        ),
        migrations.CreateModel(
            name='TrainingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.training')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
