# Generated by Django 4.2.30 on 2026-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0013_pricemodel_remove_machine_premium_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemforrent',
            old_name='full_price',
            new_name='full_price_old',
        ),
        migrations.AddField(
            model_name='training',
            name='full_price',
            field=models.DecimalField(decimal_places=2, help_text='for 30 min', max_digits=6, null=True, verbose_name='Tarifs'),
        ),
    ]
