# Generated by Django 3.2.15 on 2022-10-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('machines', '0014_auto_20221023_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachinesListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='machines_machineslistpluginmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tarif membre'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='link_text',
            field=models.CharField(max_length=255, verbose_name='Text lien'),
        ),
    ]
