# Generated by Django 4.2.30 on 2026-06-16 15:17

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0014_rename_full_price_itemforrent_full_price_old_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql = """insert into machines_pricemodel
select mi.id, dct.id 
from django_content_type dct 
left join machines_itemforrent mi on 1 = 1
where dct.app_label = 'machines' and dct.model = 'linearpricemodel';
select setval('machines_pricemodel_id_seq', max(mp.id) + 1) from machines_pricemodel mp;               

insert into machines_linearpricemodel (pricemodel_ptr_id, full_price)
select pm.id, mi.full_price_old from machines_pricemodel pm
join machines_itemforrent mi on mi.id = pm.id;

update machines_machine
set price = mi.id
from (select mi.id from machines_itemforrent mi 
join machines_machine mm on mm.itemforrent_ptr_id = mi.id) as mi;""",
            reverse_sql = ""
        )
    ]

