# Generated by Django 3.2.16 on 2022-10-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0015_auto_20221029_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='toolmachine',
            old_name='tool',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='tooltraining',
            old_name='tool',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='itemforrent',
            name='premium_price',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='subscriber_price',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='support',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='training',
            name='support',
        ),
        migrations.AddField(
            model_name='machine',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tarif membre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('available', 'Available'), ('maintenance', 'Maintenance')], default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolmachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine'),
        ),
        migrations.RenameModel(
            old_name='Tool',
            new_name='Card',
        ),
        migrations.DeleteModel(
            name='MachineTodoPoint',
        ),
        migrations.AddField(
            model_name='highlightmachine',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.card'),
        ),
        migrations.AddField(
            model_name='highlightmachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='material',
            field=models.ManyToManyField(to='machines.Material'),
        ),
        migrations.AddField(
            model_name='machine',
            name='workshop',
            field=models.ManyToManyField(to='machines.Workshop'),
        ),
    ]
