# Generated by Django 4.2.30 on 2026-06-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0015_copy_linear_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemforrent',
            name='full_price_old',
        ),
    ]
