# Generated by Django 3.2.16 on 2022-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_auto_20221030_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinegroup',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='machinecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='machinegroup',
            name='description',
        ),
        migrations.AddField(
            model_name='machinecategory',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
