# Generated by Django 3.2.16 on 2022-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0017_auto_20221030_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='material',
            field=models.ManyToManyField(blank=True, to='machines.Material'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workshop',
            field=models.ManyToManyField(blank=True, to='machines.Workshop'),
        ),
    ]
