# Generated by Django 3.2.16 on 2022-10-30 16:38

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0018_auto_20221030_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='training',
            name='header',
        ),
        migrations.RemoveField(
            model_name='training',
            name='photo',
        ),
        migrations.AddField(
            model_name='itemforrent',
            name='header',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Chapeau'),
        ),
        migrations.AddField(
            model_name='itemforrent',
            name='photo',
            field=models.ImageField(default='', upload_to='trainings', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
