# Generated by Django 3.2.16 on 2022-10-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0019_auto_20221030_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.URLField(blank=True, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='card',
            name='link_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text lien'),
        ),
        migrations.AlterField(
            model_name='itemforrent',
            name='photo',
            field=models.ImageField(upload_to='img', verbose_name='Photo'),
        ),
    ]
