# Generated by Django 3.2.16 on 2022-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0020_auto_20221030_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bootstrap_icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons', verbose_name='Icon'),
        ),
    ]
