# Generated by Django 3.2.16 on 2022-10-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0022_alter_card_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url_resolver',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
