# Generated by Django 3.2.16 on 2022-10-31 19:18

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0025_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='color',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='title',
        ),
        migrations.RemoveField(
            model_name='training',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='training',
            name='color',
        ),
        migrations.RemoveField(
            model_name='training',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='training',
            name='title',
        ),
        migrations.AddField(
            model_name='itemforrent',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AddField(
            model_name='itemforrent',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AddField(
            model_name='itemforrent',
            name='desc',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='itemforrent',
            name='title',
            field=models.CharField(default='My title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinecategory'),
        ),
    ]
