# Generated by Django 3.2.16 on 2022-10-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0026_auto_20221031_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spec',
        ),
    ]
