# Generated by Django 3.2.16 on 2022-11-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0027_remove_machine_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Carte', 'verbose_name_plural': 'Cartes'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='highlightmachine',
            options={'verbose_name': 'Atouts machine', 'verbose_name_plural': 'Atouts machine'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AlterModelOptions(
            name='machinecategory',
            options={'verbose_name': 'Catégorie de machine', 'verbose_name_plural': 'Catégories de machine'},
        ),
        migrations.AlterModelOptions(
            name='machinegroup',
            options={'verbose_name': 'Groupe de machine', 'verbose_name_plural': 'Groupes de machine'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Spécification', 'verbose_name_plural': 'Spécifications'},
        ),
        migrations.AlterModelOptions(
            name='toolmachine',
            options={'verbose_name': 'Outil machine', 'verbose_name_plural': 'Outils machines'},
        ),
        migrations.AlterModelOptions(
            name='tooltraining',
            options={'verbose_name': 'Outil de formation', 'verbose_name_plural': 'Outils de formation'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Atelier', 'verbose_name_plural': 'Ateliers'},
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icone'),
        ),
    ]
