version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
        - .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./interlab:/code/interlab
      - ./accounts:/code/accounts
      - ./newsletter:/code/newsletter
      - ./frontend:/code/frontend
      - ./locale:/code/locale
      - ./build:/code/build
    ports:
      - "8000:8000"
      - 3000:3000
    depends_on:
      - db
  celery-worker:
    build: .
    command: celery -A interlab worker -l INFO
    volumes:
      - ./interlab:/code/interlab
      - ./accounts:/code/accounts
    env_file:
      - .env
    depends_on: 
      - web
      - redis
      - db
  celery-beat:
    build: .
    command: celery -A interlab beat -l INFO
    volumes:
      - ./interlab:/code/interlab
      - ./accounts:/code/accounts
    env_file:
      - .env
    depends_on: 
      - web
      - redis
      - db

  redis:
    image: redis:alpine
