version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
        - .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./accounts:/code/accounts
      - ./build:/code/build
      - ./fabcal:/code/fabcal
      - ./api:/code/api
      - ./frontend:/code/frontend
      - ./interlab:/code/interlab
      - ./locale:/code/locale
      - ./machines:/code/machines
      - ./media:/code/media
      - ./newsletter:/code/newsletter
      - ./openings:/code/openings
      - ./share:/code/share
      - ./payments:/code/payments
    ports:
      - "8000:8000"
    depends_on:
      - db
