version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
        - .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./interlab:/code/interlab
      - ./user_profile:/code/user_profile
      - ./frontend:/code/frontend
      - ./locale:/code/locale
    ports:
      - "8000:8000"
    depends_on:
      - db

