version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
        - .env
    ports:
      - "6543:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./interlab:/code/interlab
      - ./accounts:/code/accounts
      - ./newsletter:/code/newsletter
      - ./frontend:/code/frontend
      - ./locale:/code/locale
    ports:
      - "8000:8000"
      - 3000:3000
    depends_on:
      - db

