services:
  db:
    image: postgres:18
#    command: su - postgres -c pg_upgrade
    volumes:
      - ./data/db:/var/lib/postgresql
    env_file:
        - .env
    ports:
      - "127.0.0.1:5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./accounts:/code/accounts
      - ./build:/code/build
      - ./fabcal:/code/fabcal
      - ./api:/code/api
      - ./frontend:/code/frontend
      - ./interlab:/code/interlab
      - ./locale:/code/locale
      - ./machines:/code/machines
      - ./media:/code/media
      - ./newsletter:/code/newsletter
      - ./openings:/code/openings
      - ./share:/code/share
      - ./payments:/code/payments
      - ./plugins:/code/plugins
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db
