# Generated by Django 4.2.13 on 2024-05-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('cms', '0036_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypewriterPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('strings', models.TextField(help_text='Enter the strings for the typewriter effect, separated by commas.', verbose_name='Strings')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
