# Generated by Django 3.2.13 on 2022-05-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('is_open_to_reservation', models.BooleanField()),
                ('is_open_to_questions', models.BooleanField()),
                ('is_reservation_mandatory', models.BooleanField()),
            ],
        ),
    ]
