# Generated by Django 3.2.16 on 2022-11-16 21:02

import colorfield.fields
from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    replaces = [('openings', '0001_initial'), ('openings', '0002_auto_20220530_1458'), ('openings', '0003_alter_opening_options'), ('openings', '0004_opening_is_public'), ('openings', '0005_event'), ('openings', '0006_event_is_active'), ('openings', '0007_event_is_on_site'), ('openings', '0008_auto_20220712_2147'), ('openings', '0009_auto_20220712_2148'), ('openings', '0010_auto_20221016_2147')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('lead', models.TextField(blank=True, null=True)),
                ('desc', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description')),
                ('location', models.CharField(default='Fablab', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_on_site', models.BooleanField(default=True)),
                ('background_color', colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')])),
                ('color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')])),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description')),
                ('is_open_to_reservation', models.BooleanField()),
                ('is_open_to_questions', models.BooleanField()),
                ('is_reservation_mandatory', models.BooleanField()),
                ('background_color', colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')])),
                ('color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')])),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opening',
                'verbose_name_plural': 'Openings',
            },
        ),
    ]
