# Generated by Django 3.2.16 on 2022-11-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_PR130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_on_site',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='opening',
            name='is_public',
            field=models.BooleanField(),
        ),
    ]
