# Generated by Django 3.2.16 on 2022-12-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_auto_20221116_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
