# Generated by Django 3.2.13 on 2022-05-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_auto_20220530_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opening',
            options={'verbose_name': 'Opening', 'verbose_name_plural': 'Openings'},
        ),
    ]
