# Generated by Django 3.2.18 on 2023-02-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_auto_20221222_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
