# Generated by Django 3.2.13 on 2022-05-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_alter_opening_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='is_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
