# Generated by Django 3.2.13 on 2022-07-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
