# Generated by Django 3.2.13 on 2022-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0006_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_on_site',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
