# Generated by Django 3.2.13 on 2022-07-12 21:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0008_auto_20220712_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AlterField(
            model_name='opening',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0b1783', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
        migrations.AlterField(
            model_name='opening',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=[('#0b1783', 'blue'), ('#ddf9ff', 'blue-light'), ('#e3005c', 'red'), ('#ffe8e0', 'red-light'), ('#00a59f', 'green'), ('#e4f2e5', 'green-light')]),
        ),
    ]
