# Generated by Django 3.2.15 on 2022-10-16 21:47

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0009_auto_20220712_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='desc',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
    ]
