# Generated by Django 3.1.13 on 2021-10-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20211003_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='sort',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='star_flag',
            field=models.BooleanField(),
        ),
    ]
