# Generated by Django 3.1.13 on 2021-10-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20211003_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='access_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='duration',
            field=models.PositiveSmallIntegerField(default=360),
        ),
    ]
