# Generated by Django 3.1.13 on 2021-08-23 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptioncategory',
            options={'verbose_name_plural': 'Subscription Categories'},
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='accounts',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncategory',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncategory',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncategory',
            name='star_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscriptioncategory'),
        ),
    ]
