# Generated by Django 3.1.14 on 2022-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='duration',
            field=models.PositiveSmallIntegerField(default=365),
        ),
    ]
