# Generated by Django 3.1.14 on 2022-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220312_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='price',
            field=models.IntegerField(),
        ),
    ]
