# Generated by Django 3.2.16 on 2023-01-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221222_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
