# Generated by Django 3.2.16 on 2023-01-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220320_2116'),
        ('accounts', '0003_auto_20221222_0802'),
    ]

    operations = [
    ]
