# Generated by Django 3.2.17 on 2023-02-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_discord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='discord',
            new_name='public_contact',
        ),
        migrations.AddField(
            model_name='profile',
            name='public_contact_plateform',
            field=models.CharField(choices=[('discord', 'Discord'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('email', 'e-mail')], default='discord', max_length=255),
            preserve_default=False,
        ),
    ]
