# Generated by Django 3.2.18 on 2023-02-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0005_auto_20230203_2054'), ('accounts', '0006_alter_profile_public_contact_plateform'), ('accounts', '0007_auto_20230215_2239')]

    dependencies = [
        ('accounts', '0004_profile_discord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='discord',
            new_name='public_contact',
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public contact'),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_contact_plateform',
            field=models.CharField(blank=True, choices=[('discord', 'Discord'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('envelope', 'e-mail')], max_length=255, null=True, verbose_name='Plublic chanel'),
        ),
    ]
