# Generated by Django 3.2.18 on 2023-02-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220320_2116'),
        ('accounts', '0005_auto_20230203_2054_squashed_0007_auto_20230215_2239'),
    ]

    operations = [
    ]
