# Generated by Django 3.2.17 on 2023-02-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230203_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_contact_plateform',
            field=models.CharField(blank=True, choices=[('discord', 'Discord'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('envelope', 'e-mail')], max_length=255, null=True),
        ),
    ]
