# Generated by Django 3.2.18 on 2023-03-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20230224_2339'),
        ('accounts', '0007_alter_profile_phone_number'),
    ]

    operations = [
    ]
