# Generated by Django 3.1.13 on 2021-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211109_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='category',
            new_name='subscription_category',
        ),
        migrations.RenameField(
            model_name='subscriptioncategory',
            old_name='access_number',
            new_name='default_access_number',
        ),
        migrations.AddField(
            model_name='subscription',
            name='access_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
