# Generated by Django 3.2.15 on 2022-10-14 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabcal', '0003_trainingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingslot',
            name='registration_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='registrations',
            field=models.ManyToManyField(blank=True, null=True, related_name='training_registration_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
