# Generated by Django 3.2.15 on 2022-10-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0004_auto_20221014_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingslot',
            options={'verbose_name': 'Training Slot', 'verbose_name_plural': 'Training Slots'},
        ),
    ]
