# Generated by Django 4.2.13 on 2024-05-22 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabcal', '0004_alter_calendaropeningspluginmodel_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingslot',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='training_registration_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
