# Generated by Django 3.2.13 on 2022-06-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0004_calendaropeningspluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingslot',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
