# Generated by Django 4.2.13 on 2024-07-06 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fabcal.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabcal', '0005_alter_trainingslot_registrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventslot',
            old_name='has_registration',
            new_name='registration_required',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='registrations',
        ),
        migrations.AddField(
            model_name='eventslot',
            name='additional_info',
            field=models.TextField(blank=True, help_text="Information supplémentaire pour l'inscription à l'événement", null=True),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='external_registration_link',
            field=models.CharField(blank=True, help_text='Enter URL or email address', max_length=2048, null=True, validators=[fabcal.validators.url_or_email_validator]),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('external', 'External')], help_text='Define whether event registration is done directly on the fablab site or on the external site', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventslot',
            name='registration_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingslot',
            name='registration_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistrationEventSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_attendees', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('event_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='fabcal.eventslot')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registration_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event slot Registration',
                'verbose_name_plural': 'Event slot registrations',
            },
        ),
    ]
