# Generated by Django 4.2.13 on 2024-06-02 13:55

from django.db import migrations, models
import fabcal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0005_alter_trainingslot_registrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventslot',
            old_name='has_registration',
            new_name='registration_required',
        ),
        migrations.AddField(
            model_name='eventslot',
            name='external_registration_link',
            field=models.CharField(blank=True, help_text='Enter URL or email address', null=True, validators=[fabcal.validators.url_or_email_validator]),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('external', 'External')], help_text='Define whether event registration is done directly on the fablab site or on the external site', max_length=20, null=True),
        ),
    ]
