# Generated by Django 3.2.13 on 2022-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0006_eventslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventslot',
            old_name='has_supcritions',
            new_name='has_subscriptions',
        ),
        migrations.RenameField(
            model_name='eventslot',
            old_name='subcriptions',
            new_name='subscriptions',
        ),
        migrations.AlterField(
            model_name='eventslot',
            name='price',
            field=models.TextField(max_length=255),
        ),
    ]
