# Generated by Django 4.2.17 on 2025-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0006_rename_has_registration_eventslot_registration_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslot',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional information sent by e-mail upon registration', null=True),
        ),
    ]
