# Generated by Django 3.2.13 on 2022-06-11 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabcal', '0007_auto_20220611_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslot',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_subscription_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
