# Generated by Django 3.2.13 on 2022-06-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0005_event'),
        ('fabcal', '0008_alter_eventslot_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openings.opening'),
        ),
    ]
