# Generated by Django 3.2.13 on 2022-07-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0009_eventslot_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
