# Generated by Django 3.2.13 on 2022-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0010_alter_eventslot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='subscriptions_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
