# Generated by Django 3.2.13 on 2022-10-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabcal', '0013_eventslistpluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventslot',
            name='opening',
        ),
        migrations.AddField(
            model_name='eventslot',
            name='opening_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabcal.openingslot'),
        ),
    ]
