# Generated by Django 3.2.17 on 2023-02-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('share', '0002_alter_post_created_at'), ('share', '0003_post_url'), ('share', '0004_auto_20230203_2101')]

    dependencies = [
        ('share', '0001_squashed'),
        ('accounts', '0001_squashed_0006_alter_profile_public_contact_plateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='share', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien'),
        ),
    ]
