# Generated by Django 3.2.18 on 2023-02-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('share', '0003_post_url'), ('share', '0004_auto_20230203_2101')]

    dependencies = [
        ('accounts', '0005_auto_20230203_2054_squashed_0007_auto_20230215_2239'),
        ('share', '0001_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='share', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien'),
        ),
    ]
