# Generated by Django 3.2.16 on 2023-01-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_rename_user_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
