# Generated by Django 3.2.18 on 2023-02-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_alter_post_created_at'),
        ('share', '0003_post_url_squashed_0004_auto_20230203_2101'),
    ]

    operations = [
    ]
