name: CI

on:
  # Triggers the workflow on push or pull request events but dev and main branches
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]
    environment:
      SECRET_KEY: ci

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  # Build the docker-image containing frontend and backend
  build:
    runs-on: self-hosted
    steps:
      # Workspace checkout
      - uses: actions/checkout@v3
      
      # Generate docker image and propagate to private registry
      - name: Build staging docker image
        run: |
          touch .env
          export TAG=PR$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          docker-compose build --pull --no-cache
          docker image tag interlab_web:latest registry.fablab-chaux-de-fonds.ch/flcdf/interlab:$TAG
          docker image push registry.fablab-chaux-de-fonds.ch/flcdf/interlab:$TAG
