# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Prepare docker image tag to allow specific pull-request deployment
      - name: Get docker image tag from ref
        run: |
          export TAG=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "::set-env name=TAG::$TAG"
          
      # Runs a single command using the runners shell
      - name: Build staging docker image
        run: |
          echo $TAG
          touch .env
          docker-compose build
          docker image tag interlab_web:latest registry.fablab-chaux-de-fonds.ch/flcdf/interlab:latest
          docker image push registry.fablab-chaux-de-fonds.ch/flcdf/interlab:latest
          
