name: CI

on:
  # Triggers the workflow on push or pull request events but dev and main branches
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the docker-image containing frontend and backend
  build:
    runs-on: self-hosted
    permissions:
      contents: write 
    steps:
      # Generate docker image and propagate to private registry
      - uses: actions/checkout@v3
      - name: Build staging docker image
        run: |
          touch .env
          export TAG=PR$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          docker-compose build --pull --no-cache
          docker run --rm -u $UID:$GID -v $(pwd)/test:/code/test -e SECRET_KEY=ci interlab_web:latest test/coverage.sh
          docker image tag interlab_web:latest registry.fablab-chaux-de-fonds.ch/flcdf/interlab:$TAG
          docker image push registry.fablab-chaux-de-fonds.ch/flcdf/interlab:$TAG

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: test/html
          target-folder: coverage/${{ github.ref }}